apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    name: pdf-integration
    kind: Integration
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: pdf-integration-staging
- target:
    name: pdf-integration
    kind: ConfigMap
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: pdf-integration-staging
