apiVersion: camel.apache.org/v1
kind: Integration
metadata:
    name: logging-service
    namespace: pdf-integration
spec:
    flows:

      - from:
            uri: "kafka:pdf.received?brokers={{kafka.brokers}}"
            steps:
              - set-body:
                    simple: >
                        INSERT INTO document_log (client_id, document_id, status) VALUES ('${body.clientId}', '${body.documentId}', 'RECEIVED')
              - to: "jdbc:dataSource"

      - from:
            uri: "kafka:pdf.signed?brokers={{kafka.brokers}}"
            steps:
              - set-body:
                    simple: >
                        INSERT INTO document_log (client_id, document_id, status) VALUES ('${body.clientId}', '${body.documentId}', 'SIGNED')
              - to: "jdbc:dataSource"

      - from:
            uri: "kafka:pdf.completed?brokers={{kafka.brokers}}"
            steps:
              - set-body:
                    simple: >
                        INSERT INTO document_log (client_id, document_id, status) VALUES ('${body.clientId}', '${body.documentId}', 'COMPLETED')
              - to: "jdbc:dataSource"

      - from:
            uri: "kafka:pdf.error?brokers={{kafka.brokers}}"
            steps:
              - set-body:
                    simple: >
                        INSERT INTO document_log (client_id, document_id, status) VALUES ('${body.clientId}', '${body.documentId}', 'ERROR')
              - to: "jdbc:dataSource"
