apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: error-handler
  namespace: pdf-integration
spec:
  flows:
  - from:
      uri: "kafka:pdf.error?brokers={{kafka.brokers}}"
      steps:
      - log: "Gestion erreur pour ${body.fileName}"

      - set-body:
          simple: "${body.content}"

      - to: "sftp://{{sftp.host}}:{{sftp.port}}/{{sftp.error.dir}}?username={{sftp.username}}&password={{sftp.password}}"
