apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-cm-pdf-integration.yaml
- 02-create_sftp-to-kafka.yaml
- 03-create_sign-service.yaml
- 04-create_client-send-service.yaml
- 05-create_logging-service.yaml
- 06-create_error-handler.yaml
- 07-create_signdocument-service.yaml
- 08-create_clientsend-service.yaml
