apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    name: my-integration
    kind: Integration
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: orders-qa
